############# English navigation ##############

# main menu
[[main]]
name = "INSIGHTS"
url = "/blog"
weight = 2

[[main]]
name = "RESEARCH"
url = "/research"
weight = 3

[[main]]
name = "ABOUT"
url = "/about"
weight = 4

# footer menu
[[footer]]
name = "INSIGHTS"
url = "/blog"
weight = 1

[[footer]]
name = "RESEARCH"
url = "/research"
weight = 2

[[footer]]
name = "ABOUT"
url = "/about"
weight = 3

